apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-svc
  namespace: default
spec:
  selector:
    app: spring-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
